Repository eryajf/go-ldap-admin, pull requests merged in 2022-07, with the labels that each got.

#44 完成三方IM部门与员工字段动态关联本地字段
  README.md
  controller/a_controller.go
  controller/field_relation_controller.go
  docs/sql/go_ldap_admin.sql
  go.mod
  go.sum
  logic/a_logic.go
  logic/common_login.go
  logic/dingtalk_logic.go
  logic/feishu_logic.go
  logic/field_relation_logic.go
  logic/wecom_logic.go
  model/field_relation.go
  model/group.go
  model/request/filed_relation.go
  model/user.go
  public/client/dingtalk/client.go
  public/client/dingtalk/dingtalk.go
  public/client/feishu/feishu.go
  public/client/wechat/wecom.go
  public/common/database.go
  public/common/init_mysql_data.go
  public/tools/json.go
  routes/a_routes.go
  routes/filed_relation.go
  service/isql/a_isql.go
  service/isql/field_relation_isql.go
Labels: documentation, feature

#49 修复飞书的默认ID,添加字段关系管理的菜单导航
  public/client/feishu/feishu.go
  public/common/init_mysql_data.go
Labels: bug

#51 feature: 添加自定义字段,docker-compose添加配置文件挂载
  .gitignore
  docs/docker-compose/config/config.yml
  docs/docker-compose/docker-compose.yaml
  public/client/dingtalk/dingtalk.go
  public/client/feishu/feishu.go
  public/client/wechat/wecom.go
Labels: feature

#56 调整分组中name_pinyin的字段名
  public/client/dingtalk/dingtalk.go
  public/client/feishu/feishu.go
  public/client/wechat/wecom.go
Labels: fix

#57 feat: 添加生成加密密码接口,因为CPU架构问题,更换json库
  controller/base_controller.go
  go.mod
  go.sum
  logic/a_logic.go
  logic/base_logic.go
  model/request/base_req.go
  routes/base_routes.go
Labels: feature

#58 README中添加其他优秀项目友链
  README.md
  controller/a_controller.go
  docs/docker-compose/docker-compose.yaml
Labels: documentation

#60 feat: 支持一键导入已经在运行openldap数据的能力
  controller/group_controller.go
  controller/user_controller.go
  logic/a_logic.go
  logic/openldap_logic.go
  model/group.go
  model/request/group_req.go
  model/request/user_req.go
  public/client/openldap/openldap.go
  public/common/init_mysql_data.go
  routes/group_routes.go
  routes/user_routes.go
Labels: feature

#61 fix: 调整原ldap同步逻辑,同步之后与原来完全对齐
  logic/openldap_logic.go
  public/client/openldap/openldap.go
  public/common/init_mysql_data.go
Labels: fix

#62 feat: 三个三方IM定时任务的统一添加
  config.yml
  config/config.go
  logic/a_logic.go
  main.go
Labels: feature

#66 fix: 日志延迟+丢失问题
  service/isql/operation_log_isql.go
Labels: fix

#68 doc: 修复两个注释的小错误
  logic/dingtalk_logic.go
  logic/wecom_logic.go
Labels: documentation

#73 feat: 调整dockerfile初始化方式
  Dockerfile
  docker-start.sh
Labels: feature

#72 fix: dingding多级部门同步
  logic/a_logic.go
  logic/dingtalk_logic.go
Labels: fix

#76 fix: dockerfile
  Dockerfile
Labels: fix

#84 fix: 调整三方同步时分组与成员判断是否存在的依据,改为与ldap一致的DN
  logic/dingtalk_logic.go
  logic/feishu_logic.go
  logic/group_logic.go
  logic/openldap_logic.go
  logic/wecom_logic.go
Labels: fix

#85 fix: 飞书手机号超过11位的问题
  model/user.go
  public/client/feishu/feishu.go
Labels: fix

#86 fix: 从ldap同步过来之后groupType字段的问题
  logic/openldap_logic.go
  public/common/init_mysql_data.go
Labels: fix

#88 fix: 修复飞书根部门用户获取问题
  public/client/feishu/feishu.go
Labels: fix

#90 fix: 用户操作过程中角色权限的一些校验问题
  logic/user_logic.go
Labels: fix

#93 🎊 readme中示例截图表格化呈现
  README.md
Labels: documentation

#98 🎡 feat: 添加赞助页,以及暴漏添加部门用户失败的名字
  .github/FUNDING.yml
  logic/dingtalk_logic.go
  logic/feishu_logic.go
  logic/wecom_logic.go
Labels: feature

#99 ⚗️ readme添加徽标
  README.md
Labels: documentation
